# The URL the site will be built for
base_url = "https://ghost.livexia.xyz"
title = "Just Some Ramblings"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false # disable because too much js file update

# add feeds
generate_feed = true

# theme = "even"
# config for even
taxonomies = [
    # You can enable/disable RSS
    # {name = "categories", feed = false},
    {name = "tags", feed = false, render = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# even them
even_title = "Just Some Ramblings"
author = "livexia"
